all: greet.txt                                                                            
																					   
# The 'greeting' variable is set to the value of the 'GREETING'                           
# environment variable.                                                                   
greeting = $(GREETING)                                                                    
																					   
greet.txt:                                                                                
	 echo $(greeting) > greet.txt                     

$(MYTARGET):																			  
	 echo "This is my target" > $(MYTARGET)
